# This is a basic workflow to help you get started with Actions

name: Continueous Deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Build static js
        run: npm run build --if-present

      - name: Copy file to build folder
        run: cp CNAME build/

      - name: Deploy to GH Pages
        run: |
          git config --global user.email "sharifrafidurrahman@gmail.com"
          git config --global user.name "sharifrafid"
          git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/obboy/obboy.github.io.git
          CI=false npm run deploy
